//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DailyReportToolEntities : DbContext
    {
        public DailyReportToolEntities()
            : base("name=DailyReportToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DealerTable> DealerTables { get; set; }
        public virtual DbSet<DistributorTable> DistributorTables { get; set; }
        public virtual DbSet<TempData> TempDatas { get; set; }
    }
}
