//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerTable
    {
        public int DealerID { get; set; }
        public string DealerName { get; set; }
        public string MobileNo { get; set; }
        public string Place { get; set; }
    }
}
